//! L6-08: Prompt Template Registry — strategy-aware prompt templates.
//!
//! Defines strategy types and system prompts. Domain-specific extraction
//! prompts are now generated by `DomainContract` (L6-10).
//!
//! STR-01: LegacyJson eliminated — SLM does ONE thing per call, code orchestrates.
//! STR-02: Domain prompts migrated to DomainContract (single source of truth).

use std::fmt;

use serde::{Deserialize, Serialize};

// ═══════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════

/// Prompt strategy kinds — element-focused extraction (BM-05/06).
///
/// Both strategies have 0% degeneration on all configurations.
/// The SLM does ONE thing per call. The CODE orchestrates.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PromptStrategyKind {
    /// ~25-token single-domain markdown list (0% degen on all configs).
    MarkdownList,
    /// Two-phase: enumerate items + drill each field (~15 tokens each).
    IterativeDrill,
}

impl fmt::Display for PromptStrategyKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MarkdownList => write!(f, "markdown_list"),
            Self::IterativeDrill => write!(f, "iterative_drill"),
        }
    }
}

/// Document extraction domains (7 domains from the JSON schema).
///
/// Distinct from `ExtractionDomain` (batch_extraction), which covers
/// chat-based extraction (symptom, medication, appointment).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DocumentDomain {
    Medications,
    LabResults,
    Diagnoses,
    Allergies,
    Procedures,
    Referrals,
    Instructions,
}

impl DocumentDomain {
    /// All 7 document domains.
    pub fn all() -> &'static [DocumentDomain] {
        &[
            Self::Medications,
            Self::LabResults,
            Self::Diagnoses,
            Self::Allergies,
            Self::Procedures,
            Self::Referrals,
            Self::Instructions,
        ]
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Medications => "medications",
            Self::LabResults => "lab_results",
            Self::Diagnoses => "diagnoses",
            Self::Allergies => "allergies",
            Self::Procedures => "procedures",
            Self::Referrals => "referrals",
            Self::Instructions => "instructions",
        }
    }
}

impl fmt::Display for DocumentDomain {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

// ═══════════════════════════════════════════════════════════
// System prompts
// ═══════════════════════════════════════════════════════════

const MARKDOWN_LIST_SYSTEM: &str = "\
You are a medical document assistant. Extract ONLY information explicitly \
present in the document. NEVER add interpretation, infer information, or \
fabricate data not directly written. Output as a simple markdown list. \
Preserve the original language of the document.";

const ITERATIVE_DRILL_SYSTEM: &str = "\
You are a medical document assistant. Answer questions about this document. \
Extract ONLY information explicitly present. NEVER infer or add information \
not directly written. Answer concisely. Preserve the original language.";

/// Get the system prompt for a strategy kind.
pub fn system_prompt(kind: PromptStrategyKind) -> &'static str {
    match kind {
        PromptStrategyKind::MarkdownList => MARKDOWN_LIST_SYSTEM,
        PromptStrategyKind::IterativeDrill => ITERATIVE_DRILL_SYSTEM,
    }
}

// ═══════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    // ── System prompts ───────────────────────────────────

    #[test]
    fn markdown_list_system_prompt_correct() {
        let sp = system_prompt(PromptStrategyKind::MarkdownList);
        assert!(sp.contains("medical document"));
        assert!(sp.contains("ONLY"));
        assert!(sp.contains("markdown list"));
        assert!(sp.contains("original language"));
    }

    #[test]
    fn iterative_drill_system_prompt_correct() {
        let sp = system_prompt(PromptStrategyKind::IterativeDrill);
        assert!(sp.contains("Answer questions"));
        assert!(sp.contains("ONLY"));
        assert!(sp.contains("original language"));
    }

    #[test]
    fn system_prompts_are_concise() {
        for kind in [PromptStrategyKind::MarkdownList, PromptStrategyKind::IterativeDrill] {
            let sp = system_prompt(kind);
            assert!(sp.len() < 500, "System prompt for {kind} too long: {} chars", sp.len());
        }
    }

    // ── Display / Serialization ──────────────────────────

    #[test]
    fn strategy_kind_display() {
        assert_eq!(format!("{}", PromptStrategyKind::MarkdownList), "markdown_list");
        assert_eq!(format!("{}", PromptStrategyKind::IterativeDrill), "iterative_drill");
    }

    #[test]
    fn document_domain_display() {
        assert_eq!(format!("{}", DocumentDomain::Medications), "medications");
        assert_eq!(format!("{}", DocumentDomain::LabResults), "lab_results");
    }

    #[test]
    fn strategy_kind_serializes() {
        let json = serde_json::to_string(&PromptStrategyKind::MarkdownList).unwrap();
        assert_eq!(json, "\"markdown_list\"");
    }

    #[test]
    fn document_domain_serializes() {
        let json = serde_json::to_string(&DocumentDomain::LabResults).unwrap();
        assert_eq!(json, "\"lab_results\"");
    }
}
